[program:celery-worker]
command=/home/ubuntu/ZJOJ/.venv/bin/celery -A ZJOJ worker --loglevel=info --concurrency=2
directory=/home/ubuntu/ZJOJ
environment=DJANGO_SETTINGS_MODULE="ZJOJ.settings_production"
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/zjoj/celery_worker.log
stderr_logfile=/var/log/zjoj/celery_worker_error.log
