[program:zjoj]
command=/home/ubuntu/ZJOJ/.venv/bin/gunicorn -c /home/ubuntu/ZJOJ/gunicorn_config.py ZJOJ.wsgi:application
directory=/home/ubuntu/ZJOJ
environment=DJANGO_SETTINGS_MODULE="ZJOJ.settings_production"
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/zjoj/supervisor_stdout.log
stderr_logfile=/var/log/zjoj/supervisor_stderr.log
