# Generated by Django 6.0.3 on 2026-04-20 01:51

import apps.ojauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ojauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ojuser",
            name="uid",
            field=models.CharField(
                default=apps.ojauth.models.generate_short_uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                verbose_name="UID",
            ),
        ),
    ]
