# Generated by Django 6.0.3 on 2026-04-24 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ojauth", "0002_alter_ojuser_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ojuser",
            name="avatar",
            field=models.URLField(blank=True, default="", verbose_name="头像URL"),
        ),
        migrations.AddField(
            model_name="ojuser",
            name="bio",
            field=models.TextField(blank=True, default="", verbose_name="个人简介"),
        ),
        migrations.AddField(
            model_name="ojuser",
            name="grade",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="年级/班级"
            ),
        ),
        migrations.AddField(
            model_name="ojuser",
            name="role",
            field=models.IntegerField(
                choices=[(1, "学生"), (2, "教练"), (3, "管理员")],
                default=1,
                verbose_name="用户角色",
            ),
        ),
        migrations.AddField(
            model_name="ojuser",
            name="school",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="学校"
            ),
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="班级名称")),
                ("school", models.CharField(max_length=200, verbose_name="学校")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="班级描述"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="班主任/教练",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级",
                "verbose_name_plural": "班级",
                "db_table": "ojauth_class",
                "unique_together": {("name", "school")},
            },
        ),
        migrations.CreateModel(
            name="ClassMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "join_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="ojauth.class",
                        verbose_name="班级",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "班级成员",
                "verbose_name_plural": "班级成员",
                "db_table": "ojauth_class_member",
                "unique_together": {("class_obj", "user")},
            },
        ),
    ]
