# Generated by Django 6.0.3 on 2026-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ojauth", "0003_ojuser_avatar_ojuser_bio_ojuser_grade_ojuser_role_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="ojuser",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="ojuser",
            name="school",
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="班级名称"
            ),
        ),
        migrations.RemoveField(
            model_name="class",
            name="school",
        ),
    ]
