# Generated by Django 6.0.3 on 2026-04-15 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="提交ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("java", "Java"),
                            ("python3", "Python 3"),
                            ("python2", "Python 2"),
                        ],
                        max_length=20,
                        verbose_name="编程语言",
                    ),
                ),
                ("code", models.TextField(verbose_name="源代码")),
                (
                    "code_length",
                    models.PositiveIntegerField(default=0, verbose_name="代码长度"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "等待评测"),
                            (1, "评测中"),
                            (2, "已完成"),
                            (3, "编译错误"),
                            (4, "系统错误"),
                        ],
                        default=0,
                        verbose_name="评测状态",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                            ("CE", "Compilation Error"),
                            ("SE", "System Error"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="评测结果",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0, verbose_name="得分")),
                (
                    "execution_time",
                    models.PositiveIntegerField(default=0, verbose_name="运行时间(ms)"),
                ),
                (
                    "memory_usage",
                    models.PositiveIntegerField(default=0, verbose_name="内存使用(KB)"),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "judge_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="评测时间"
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problem.problem",
                        verbose_name="所属题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提交记录",
                "verbose_name_plural": "提交记录",
                "db_table": "submission",
                "ordering": ["-submit_time"],
            },
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_case_id", models.PositiveIntegerField(verbose_name="测试点ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Accepted"),
                            ("WA", "Wrong Answer"),
                            ("TLE", "Time Limit Exceeded"),
                            ("MLE", "Memory Limit Exceeded"),
                            ("RE", "Runtime Error"),
                        ],
                        max_length=10,
                        verbose_name="测试点状态",
                    ),
                ),
                (
                    "execution_time",
                    models.PositiveIntegerField(default=0, verbose_name="运行时间(ms)"),
                ),
                (
                    "memory_usage",
                    models.PositiveIntegerField(default=0, verbose_name="内存使用(KB)"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(default=0, verbose_name="该测试点得分"),
                ),
                (
                    "message",
                    models.TextField(blank=True, default="", verbose_name="详细信息"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_case_results",
                        to="problem.submission",
                        verbose_name="所属提交",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试点结果",
                "verbose_name_plural": "测试点结果",
                "db_table": "test_case_result",
                "ordering": ["test_case_id"],
            },
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["-submit_time"], name="submission_submit__0edcf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["user", "-submit_time"], name="submission_user_id_bfde67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["problem", "-submit_time"], name="submission_problem_9bb140_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcaseresult",
            unique_together={("submission", "test_case_id")},
        ),
    ]
