# Generated by Django 6.0.3 on 2026-04-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0002_submission_testcaseresult_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="problem",
            old_name="tag",
            new_name="tags",
        ),
    ]
