# Generated by Django 6.0.3 on 2026-04-15 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problem", "0002_submission_testcaseresult_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("algorithm", "算法讲解"),
                            ("solution", "题解"),
                            ("template", "代码模板"),
                            ("concept", "概念说明"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, max_length=500, verbose_name="来源"),
                ),
                (
                    "vector_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="向量ID"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="problem.tag", verbose_name="标签"
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库文档",
                "verbose_name_plural": "知识库文档",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_quota",
                    models.IntegerField(default=50, verbose_name="每日配额"),
                ),
                ("used_today", models.IntegerField(default=0, verbose_name="今日已用")),
                (
                    "last_reset_date",
                    models.DateField(auto_now_add=True, verbose_name="上次重置日期"),
                ),
                (
                    "max_history",
                    models.IntegerField(default=100, verbose_name="最大历史记录数"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户AI配置",
                "verbose_name_plural": "用户AI配置",
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="问题")),
                ("answer", models.TextField(verbose_name="答案")),
                ("sources", models.JSONField(default=list, verbose_name="引用来源")),
                (
                    "model_used",
                    models.CharField(
                        default="glm-4", max_length=50, verbose_name="使用的模型"
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="消耗Token数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话历史",
                "verbose_name_plural": "对话历史",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_assistan_user_id_e58337_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField(verbose_name="时间窗口开始")),
                (
                    "request_count",
                    models.IntegerField(default=0, verbose_name="请求次数"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "频率限制",
                "verbose_name_plural": "频率限制",
                "unique_together": {("user", "window_start")},
            },
        ),
    ]
