# Generated by Django 6.0.3 on 2026-04-24 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
        ("ojauth", "0004_alter_class_unique_together_remove_ojuser_grade_and_more"),
        ("problem", "0004_alter_problem_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="error_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="错误类型（WA/TLE/MLE/RE/CE）",
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_docs",
                to="problem.problem",
                verbose_name="关联题目",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgebase",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("algorithm", "算法讲解"),
                    ("solution", "题解"),
                    ("template", "代码模板"),
                    ("concept", "概念说明"),
                    ("error_solution", "错误解决方案"),
                ],
                max_length=20,
                verbose_name="类型",
            ),
        ),
        migrations.CreateModel(
            name="APICache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="缓存键"
                    ),
                ),
                ("response_data", models.JSONField(verbose_name="响应数据")),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "API缓存",
                "verbose_name_plural": "API缓存",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="ai_assistan_expires_2c682c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("student", "学生个性报告"),
                            ("class", "班级共性报告"),
                        ],
                        max_length=10,
                        verbose_name="报告类型",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="统计开始日期")),
                ("period_end", models.DateField(verbose_name="统计结束日期")),
                ("summary", models.TextField(verbose_name="总结内容")),
                ("statistics", models.JSONField(default=dict, verbose_name="统计数据")),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="建议列表"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "class_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_reports",
                        to="ojauth.class",
                        verbose_name="班级（仅班级报告）",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学情报告",
                "verbose_name_plural": "学情报告",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-generated_at"],
                        name="ai_assistan_user_id_b5b032_idx",
                    ),
                    models.Index(
                        fields=["class_obj", "-generated_at"],
                        name="ai_assistan_class_o_487c20_idx",
                    ),
                ],
            },
        ),
    ]
